name: BUILD CHECK CI

on:
  pull_request:
    branches: ["main", "release/**"]

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    env:
      # 필요하면 사용 (예: JWT 서명키)
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 테스트 포함하려면 -x test 제거
      - name: Build with Gradle
        run: ./gradlew clean build -x test